#!/bin/sh
# Copy fp_math.h + microgpt_int.c from the repo root into this harness,
# bake the repo's model.mgw into include/model_mgw.h (8-byte-aligned const
# array -> XIP flash on the RP2040), stamp the tree state into
# include/build_info.h, and pin the expected sample-stream hash into
# include/gpt_pin.h.
#
# Pin provenance: the pin is the HOST's GPT_SAMPLES_HASH, computed here at
# prepare time by building hostref/host_main.c against the SAME copied
# sources and the SAME entry points the firmware calls, native __int128
# backend. On-target PASS therefore means the RP2040 reproduced the exact
# 20 names the Mac's training run sampled — full inference path, PRNG
# stream included, across backend and ISA.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../../../.." && pwd)
mkdir -p "$HERE/src" "$HERE/include"
cp "$REPO/microgpt_int.c" "$HERE/src/microgpt_int.c"
cp "$REPO/fp_math.h"      "$HERE/include/fp_math.h"

MGW="$REPO/model.mgw"
if [ ! -f "$MGW" ]; then
    echo "prepare: FAIL — $MGW not found (train one: ./gpt_int --save model.mgw)" >&2
    exit 1
fi
python3 - "$MGW" "$HERE/include/model_mgw.h" <<'EOF'
import sys
data = open(sys.argv[1], "rb").read()
with open(sys.argv[2], "w") as f:
    f.write("/* generated by prepare.sh from model.mgw — do not edit */\n")
    f.write("__attribute__((aligned(8))) static const unsigned char model_mgw[] = {\n")
    for i in range(0, len(data), 16):
        f.write("  " + "".join("0x%02x," % b for b in data[i:i+16]) + "\n")
    f.write("};\n")
    f.write("static const unsigned int model_mgw_len = %du;\n" % len(data))
EOF

COMMIT=$(git -C "$REPO" rev-parse --short=12 HEAD)
DIRTY=""
# Dirty is scoped to exactly the library files copied above.
if ! git -C "$REPO" diff --quiet HEAD -- microgpt_int.c fp_math.h 2>/dev/null; then
    DIRTY="-dirty"
fi
printf '#define BUILD_COMMIT "%s%s"\n' "$COMMIT" "$DIRTY" > "$HERE/include/build_info.h"

# Host reference build -> run -> extract the pin.
HOSTDIR="$HERE/.hostref"
mkdir -p "$HOSTDIR"
cc -std=c11 -O2 -fwrapv -Wno-unused-function -DMGPT_NO_TRAIN -DMGPT_NO_MAIN \
    -I"$HERE/include" \
    "$HERE/hostref/host_main.c" "$HERE/src/microgpt_int.c" \
    -o "$HOSTDIR/host_gpt"
HOST_OUT=$("$HOSTDIR/host_gpt" "$MGW")
echo "$HOST_OUT"
PIN_HASH=$(printf '%s\n' "$HOST_OUT" \
    | sed -n 's/^GPT_SAMPLES_HASH=\([0-9a-f]\{16\}\)$/\1/p')
if [ -z "$PIN_HASH" ]; then
    echo "prepare: FAIL — host reference did not print GPT_SAMPLES_HASH" >&2
    exit 1
fi
printf '#define PINNED_HASH 0x%sULL\n' "$PIN_HASH" > "$HERE/include/gpt_pin.h"

echo "prepared: sources from $REPO (tree $COMMIT$DIRTY, host pin 0x$PIN_HASH)"
